import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { SchoolScopeService } from '../common/services/school-scope.service';
@Injectable()
export class ProjectsService{
 constructor(private prisma:PrismaService,private scope:SchoolScopeService){}
 private async schoolForCreate(user:any,requestedSchoolId?:string){const schoolId=user.roles?.includes('SUPER_ADMIN')?requestedSchoolId:user.schoolId;if(!schoolId)throw new BadRequestException('schoolId is required for this account');const school=await this.prisma.school.findFirst({where:{id:schoolId,organizationId:user.organizationId}});if(!school)throw new ForbiddenException('School is outside organization scope');this.scope.assertSameSchool(user,school.id);return school}
 async list(user:any){return this.prisma.project.findMany({where:user.roles?.includes('SUPER_ADMIN')?{school:{organizationId:user.organizationId}}:{schoolId:user.schoolId},include:{activities:true,kpis:true,members:{include:{user:{select:{id:true,displayName:true,email:true}}}}},orderBy:[{fiscalYear:{yearBE:'desc'}},{code:'asc'}]})}
 async create(user:any,d:any){const school=await this.schoolForCreate(user,d.schoolId);const fy=await this.prisma.fiscalYear.findFirst({where:{id:d.fiscalYearId,organizationId:user.organizationId}});if(!fy)throw new BadRequestException('Fiscal year is outside organization scope');try{const project=await this.prisma.project.create({data:{schoolId:school.id,fiscalYearId:fy.id,code:d.code,name:d.name,approvedBudget:new Prisma.Decimal(d.approvedBudget??0)}});await this.prisma.auditLog.create({data:{organizationId:user.organizationId,schoolId:school.id,actorUserId:user.id,action:'PROJECT_CREATED',entityType:'Project',entityId:project.id,metadata:{code:project.code,name:project.name}}});return project}catch(e:any){if(e?.code==='P2002')throw new ConflictException('Project code already exists for this school and fiscal year');throw e}}
 async get(user:any,id:string){const x=await this.prisma.project.findFirst({where:{id,school:{organizationId:user.organizationId}},include:{fiscalYear:true,school:true,activities:{include:{budgets:{include:{budgetPocket:{include:{budgetPool:true}}}},expenses:true,reports:true}},kpis:true,members:{include:{user:{select:{id:true,displayName:true,email:true}}}}}});if(!x)throw new NotFoundException('Project not found');this.scope.assertSameSchool(user,x.schoolId);return x}
 async update(user:any,id:string,d:any){const x=await this.get(user,id);if(!['DRAFT','RETURNED','REJECTED'].includes(x.status))throw new BadRequestException('Project can only be edited in DRAFT, RETURNED or REJECTED state');const project=await this.prisma.project.update({where:{id},data:{...(d.code!==undefined?{code:d.code}:{}),...(d.name!==undefined?{name:d.name}:{}),...(d.approvedBudget!==undefined?{approvedBudget:new Prisma.Decimal(d.approvedBudget)}:{})}});await this.prisma.auditLog.create({data:{organizationId:user.organizationId,schoolId:x.schoolId,actorUserId:user.id,action:'PROJECT_UPDATED',entityType:'Project',entityId:id,metadata:{changed:Object.keys(d)}}});return project}
}
