import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { nextWorkflow } from '../common/domain/workflow';
import { SchoolScopeService } from '../common/services/school-scope.service';
import { WORKFLOW_APPROVER_BY_STEP, WORKFLOW_SUBMIT_ROLES } from '../common/domain/permissions';
@Injectable()
export class WorkflowService{
 constructor(private prisma:PrismaService,private scope:SchoolScopeService){}
 private can(user:any,roles:string[]){return user.roles?.some((r:string)=>roles.includes(r))}
 async start(u:any,d:any){if(d.entityType!=='Project')throw new BadRequestException('Only Project workflow is supported by this endpoint');if(!this.can(u,WORKFLOW_SUBMIT_ROLES))throw new ForbiddenException('Role cannot submit workflow');const project=await this.prisma.project.findFirst({where:{id:d.entityId,school:{organizationId:u.organizationId}}});if(!project)throw new NotFoundException('Project not found');this.scope.assertSameSchool(u,project.schoolId);if(!['DRAFT','RETURNED','REJECTED'].includes(project.status))throw new BadRequestException('Project is not ready for submission');const existing=await this.prisma.workflowInstance.findFirst({where:{entityType:'Project',entityId:project.id,status:'PENDING'}});if(existing)throw new BadRequestException('Project already has a pending workflow');return this.prisma.$transaction(async t=>{const w=await t.workflowInstance.create({data:{entityType:'Project',entityId:project.id,currentStep:1,status:'PENDING',actions:{create:{action:'SUBMIT',step:1,actorUserId:u.id,comment:d.comment}}}});await t.project.update({where:{id:project.id},data:{status:'SUBMITTED'}});await t.auditLog.create({data:{organizationId:u.organizationId,schoolId:project.schoolId,actorUserId:u.id,action:'PROJECT_SUBMITTED',entityType:'Project',entityId:project.id,metadata:{workflowId:w.id,step:1}}});return w})}
 async actionForProject(u:any,projectId:string,action:'APPROVE'|'REJECT'|'RETURN',comment?:string){const w=await this.prisma.workflowInstance.findFirst({where:{entityType:'Project',entityId:projectId,status:'PENDING'},orderBy:{createdAt:'desc'}});if(!w)throw new NotFoundException('Pending project workflow not found');return this.act(u,w.id,{action,comment})}
 async act(u:any,id:string,d:any){const w=await this.prisma.workflowInstance.findUnique({where:{id}});if(!w)throw new NotFoundException('Workflow not found');if(w.entityType!=='Project')throw new BadRequestException('Unsupported workflow entity');if(w.status!=='PENDING')throw new BadRequestException('Workflow closed');const project=await this.prisma.project.findFirst({where:{id:w.entityId,school:{organizationId:u.organizationId}}});if(!project)throw new NotFoundException('Project not found');this.scope.assertSameSchool(u,project.schoolId);const action=d.action as any;if(action==='APPROVE'&&!this.can(u,WORKFLOW_APPROVER_BY_STEP[w.currentStep]??[]))throw new ForbiddenException('Role cannot approve this workflow step');if((action==='RETURN'||action==='REJECT')&&!this.can(u,WORKFLOW_APPROVER_BY_STEP[w.currentStep]??[]))throw new ForbiddenException('Role cannot act on this workflow step');if(action==='SUBMIT'||action==='REVOKE')throw new BadRequestException('Action is not valid for a pending approval step');let next;try{next=nextWorkflow(w.currentStep,action)}catch{throw new BadRequestException('Invalid workflow action')}return this.prisma.$transaction(async t=>{await t.workflowAction.create({data:{workflowInstanceId:id,action,step:w.currentStep,actorUserId:u.id,comment:d.comment}});await t.workflowInstance.update({where:{id},data:{status:next.status,currentStep:next.currentStep}});const projectStatus=next.status==='APPROVED'?'APPROVED':next.status==='RETURNED'?'RETURNED':next.status==='REJECTED'?'REJECTED':'SUBMITTED';await t.project.update({where:{id:project.id},data:{status:projectStatus as any}});await t.auditLog.create({data:{organizationId:u.organizationId,schoolId:project.schoolId,actorUserId:u.id,action:`WORKFLOW_${action}`,entityType:'Project',entityId:project.id,metadata:{workflowId:id,step:w.currentStep,nextStatus:next.status}}});return{workflowId:id,projectId:project.id,status:next.status,currentStep:next.currentStep}})}
 async get(u:any,id:string){const w=await this.prisma.workflowInstance.findUnique({where:{id},include:{actions:true}});if(!w)throw new NotFoundException('Workflow not found');if(w.entityType==='Project'){const project=await this.prisma.project.findFirst({where:{id:w.entityId,school:{organizationId:u.organizationId}}});if(!project)throw new NotFoundException('Project not found');this.scope.assertSameSchool(u,project.schoolId)}return w}
}
