-- Initial schema generated from prisma/schema.prisma; review with Prisma before production deployment.
BEGIN;
CREATE TYPE "BudgetTransactionType" AS ENUM ('OPENING', 'ALLOCATION', 'TRANSFER_IN', 'TRANSFER_OUT', 'COMMITMENT', 'EXPENSE', 'ADJUSTMENT', 'REVERSAL');
CREATE TYPE "BudgetTransactionStatus" AS ENUM ('DRAFT', 'POSTED', 'VOID');
CREATE TYPE "ProjectStatus" AS ENUM ('DRAFT', 'SUBMITTED', 'APPROVED', 'RETURNED', 'REJECTED', 'CLOSED');
CREATE TYPE "ActivityStatus" AS ENUM ('PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED');
CREATE TYPE "WorkflowActionType" AS ENUM ('SUBMIT', 'APPROVE', 'RETURN', 'REJECT', 'REVOKE');
CREATE TYPE "Free15RuleStatus" AS ENUM ('DRAFT', 'ACTIVE', 'RETIRED');
CREATE TYPE "Free15Category" AS ENUM ('HEADCOUNT', 'TEXTBOOK', 'EQUIPMENT', 'UNIFORM', 'LEARNER_ACTIVITY');
CREATE TYPE "Free15CalculationStatus" AS ENUM ('PREVIEW', 'POSTED', 'VOID');
CREATE TYPE "WorkflowStatus" AS ENUM ('PENDING', 'APPROVED', 'RETURNED', 'REJECTED', 'CANCELLED');
CREATE TYPE "AiRiskLevel" AS ENUM ('LOW', 'MEDIUM', 'HIGH');
CREATE TABLE "Organization" ("id" TEXT NOT NULL PRIMARY KEY,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,"updatedAt" TIMESTAMPTZ NOT NULL);
CREATE UNIQUE INDEX ON "Organization" ("code");
CREATE TABLE "School" ("id" TEXT NOT NULL PRIMARY KEY,"organizationId" TEXT NOT NULL,"code" TEXT NOT NULL,"name" TEXT NOT NULL);
CREATE UNIQUE INDEX ON "School" ("organizationId", "code");
CREATE TABLE "User" ("id" TEXT NOT NULL PRIMARY KEY,"organizationId" TEXT NOT NULL,"schoolId" TEXT,"email" TEXT NOT NULL,"passwordHash" TEXT NOT NULL,"displayName" TEXT NOT NULL,"isActive" BOOLEAN DEFAULT TRUE NOT NULL,"createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,"updatedAt" TIMESTAMPTZ NOT NULL);
CREATE UNIQUE INDEX ON "User" ("email");
CREATE TABLE "Role" ("id" TEXT NOT NULL PRIMARY KEY,"organizationId" TEXT NOT NULL,"code" TEXT NOT NULL,"name" TEXT NOT NULL);
CREATE UNIQUE INDEX ON "Role" ("organizationId", "code");
CREATE TABLE "UserRole" ("userId" TEXT NOT NULL,"roleId" TEXT NOT NULL);
ALTER TABLE "UserRole" ADD PRIMARY KEY ("userId", "roleId");
CREATE TABLE "FiscalYear" ("id" TEXT NOT NULL PRIMARY KEY,"organizationId" TEXT NOT NULL,"yearBE" INTEGER NOT NULL,"startsAt" TIMESTAMPTZ NOT NULL,"endsAt" TIMESTAMPTZ NOT NULL,"isActive" BOOLEAN DEFAULT TRUE NOT NULL);
CREATE UNIQUE INDEX ON "FiscalYear" ("organizationId", "yearBE");
CREATE TABLE "AcademicYear" ("id" TEXT NOT NULL PRIMARY KEY,"organizationId" TEXT NOT NULL,"yearBE" INTEGER NOT NULL,"isActive" BOOLEAN DEFAULT TRUE NOT NULL);
CREATE UNIQUE INDEX ON "AcademicYear" ("organizationId", "yearBE");
CREATE TABLE "StudentCount" ("id" TEXT NOT NULL PRIMARY KEY,"academicYearId" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"levelCode" TEXT NOT NULL,"studentCount" INTEGER NOT NULL,"recordedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE UNIQUE INDEX ON "StudentCount" ("academicYearId", "schoolId", "levelCode");
CREATE TABLE "BudgetSource" ("id" TEXT NOT NULL PRIMARY KEY,"organizationId" TEXT NOT NULL,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT,"isActive" BOOLEAN DEFAULT TRUE NOT NULL);
CREATE UNIQUE INDEX ON "BudgetSource" ("organizationId", "code");
CREATE TABLE "BudgetPool" ("id" TEXT NOT NULL PRIMARY KEY,"schoolId" TEXT NOT NULL,"fiscalYearId" TEXT NOT NULL,"budgetSourceId" TEXT NOT NULL,"name" TEXT NOT NULL,"createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE UNIQUE INDEX ON "BudgetPool" ("schoolId", "fiscalYearId", "budgetSourceId", "name");
CREATE TABLE "BudgetPocket" ("id" TEXT NOT NULL PRIMARY KEY,"budgetPoolId" TEXT NOT NULL,"code" TEXT NOT NULL,"name" TEXT NOT NULL);
CREATE UNIQUE INDEX ON "BudgetPocket" ("budgetPoolId", "code");
CREATE TABLE "BudgetTransaction" ("id" TEXT NOT NULL PRIMARY KEY,"budgetPocketId" TEXT NOT NULL,"type" "BudgetTransactionType" NOT NULL,"status" "BudgetTransactionStatus" NOT NULL,"amount" DECIMAL(14,2) NOT NULL,"referenceType" TEXT,"referenceId" TEXT,"note" TEXT,"postedAt" TIMESTAMPTZ,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE INDEX ON "BudgetTransaction" ("budgetPocketId", "status", "postedAt");
CREATE TABLE "Project" ("id" TEXT NOT NULL PRIMARY KEY,"schoolId" TEXT NOT NULL,"fiscalYearId" TEXT NOT NULL,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"status" "ProjectStatus" NOT NULL,"approvedBudget" DECIMAL(14,2) DEFAULT 0 NOT NULL);
CREATE UNIQUE INDEX ON "Project" ("schoolId", "fiscalYearId", "code");
CREATE TABLE "Activity" ("id" TEXT NOT NULL PRIMARY KEY,"projectId" TEXT NOT NULL,"name" TEXT NOT NULL,"status" "ActivityStatus" NOT NULL,"allocatedBudget" DECIMAL(14,2) DEFAULT 0 NOT NULL);
CREATE TABLE "ActivityBudget" ("id" TEXT NOT NULL PRIMARY KEY,"activityId" TEXT NOT NULL,"budgetPocketId" TEXT NOT NULL,"amount" DECIMAL(14,2) NOT NULL);
CREATE UNIQUE INDEX ON "ActivityBudget" ("activityId", "budgetPocketId");
CREATE TABLE "Expense" ("id" TEXT NOT NULL PRIMARY KEY,"activityId" TEXT NOT NULL,"amount" DECIMAL(14,2) NOT NULL,"description" TEXT NOT NULL,"expenseDate" TIMESTAMPTZ NOT NULL,"createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE TABLE "Attachment" ("id" TEXT NOT NULL PRIMARY KEY,"expenseId" TEXT,"fileName" TEXT NOT NULL,"objectKey" TEXT NOT NULL,"sha256" TEXT,"mimeType" TEXT,"sizeBytes" INTEGER,"createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE TABLE "ActivityReport" ("id" TEXT NOT NULL PRIMARY KEY,"activityId" TEXT NOT NULL,"progressPercent" INTEGER DEFAULT 0 NOT NULL,"summary" TEXT,"reportedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE TABLE "WorkflowInstance" ("id" TEXT NOT NULL PRIMARY KEY,"entityType" TEXT NOT NULL,"entityId" TEXT NOT NULL,"currentStep" INTEGER NOT NULL,"status" TEXT NOT NULL,"createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE TABLE "WorkflowAction" ("id" TEXT NOT NULL PRIMARY KEY,"workflowInstanceId" TEXT NOT NULL,"action" "WorkflowActionType" NOT NULL,"step" INTEGER NOT NULL,"actorUserId" TEXT NOT NULL,"comment" TEXT,"createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE TABLE "AuditLog" ("id" TEXT NOT NULL PRIMARY KEY,"organizationId" TEXT NOT NULL,"schoolId" TEXT,"actorUserId" TEXT,"action" TEXT NOT NULL,"entityType" TEXT NOT NULL,"entityId" TEXT,"metadata" JSONB,"createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE INDEX ON "AuditLog" ("organizationId", "schoolId", "createdAt");
CREATE TABLE "Free15RuleSet" ("id" TEXT NOT NULL PRIMARY KEY,"organizationId" TEXT NOT NULL,"academicYearId" TEXT NOT NULL,"version" INTEGER NOT NULL,"status" "Free15RuleStatus" NOT NULL,"sourceTitle" TEXT,"sourceUrl" TEXT,"effectiveFrom" TIMESTAMPTZ,"effectiveTo" TIMESTAMPTZ,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,"updatedAt" TIMESTAMPTZ NOT NULL);
CREATE UNIQUE INDEX ON "Free15RuleSet" ("organizationId", "academicYearId", "version");
CREATE TABLE "Free15Rate" ("id" TEXT NOT NULL PRIMARY KEY,"ruleSetId" TEXT NOT NULL,"category" "Free15Category" NOT NULL,"levelCode" TEXT NOT NULL,"rate" DECIMAL(14,2) NOT NULL);
CREATE UNIQUE INDEX ON "Free15Rate" ("ruleSetId", "category", "levelCode");
CREATE TABLE "Free15Calculation" ("id" TEXT NOT NULL PRIMARY KEY,"schoolId" TEXT NOT NULL,"academicYearId" TEXT NOT NULL,"ruleSetId" TEXT NOT NULL,"status" "Free15CalculationStatus" NOT NULL,"total" DECIMAL(14,2) DEFAULT 0 NOT NULL,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,"postedAt" TIMESTAMPTZ);
CREATE TABLE "Free15CalculationItem" ("id" TEXT NOT NULL PRIMARY KEY,"calculationId" TEXT NOT NULL,"category" "Free15Category" NOT NULL,"levelCode" TEXT NOT NULL,"studentCount" INTEGER NOT NULL,"rate" DECIMAL(14,2) NOT NULL,"amount" DECIMAL(14,2) NOT NULL);
CREATE UNIQUE INDEX ON "Free15CalculationItem" ("calculationId", "category", "levelCode");
CREATE TABLE "ProjectKpi" ("id" TEXT NOT NULL PRIMARY KEY,"projectId" TEXT NOT NULL,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"targetValue" DECIMAL(14,2),"unit" TEXT,"actualValue" DECIMAL(14,2));
CREATE UNIQUE INDEX ON "ProjectKpi" ("projectId", "code");
CREATE TABLE "ProjectMember" ("projectId" TEXT NOT NULL,"userId" TEXT NOT NULL);
ALTER TABLE "ProjectMember" ADD PRIMARY KEY ("projectId", "userId");
CREATE TABLE "Regulation" ("id" TEXT NOT NULL PRIMARY KEY,"organizationId" TEXT NOT NULL,"code" TEXT NOT NULL,"title" TEXT NOT NULL);
CREATE UNIQUE INDEX ON "Regulation" ("organizationId", "code");
CREATE TABLE "RegulationVersion" ("id" TEXT NOT NULL PRIMARY KEY,"regulationId" TEXT NOT NULL,"version" TEXT NOT NULL,"effectiveFrom" TIMESTAMPTZ,"effectiveTo" TIMESTAMPTZ,"sourceUrl" TEXT,"documentHash" TEXT,"notes" TEXT);
CREATE UNIQUE INDEX ON "RegulationVersion" ("regulationId", "version");
CREATE TABLE "RegulationRule" ("id" TEXT NOT NULL PRIMARY KEY,"regulationVersionId" TEXT NOT NULL,"code" TEXT NOT NULL,"title" TEXT NOT NULL,"ruleText" TEXT NOT NULL,"priority" INTEGER NOT NULL);
CREATE UNIQUE INDEX ON "RegulationRule" ("regulationVersionId", "code");
CREATE TABLE "RuleEvidence" ("id" TEXT NOT NULL PRIMARY KEY,"regulationRuleId" TEXT NOT NULL,"sourceLocator" TEXT NOT NULL,"excerpt" TEXT);
CREATE TABLE "AiAuditLog" ("id" TEXT NOT NULL PRIMARY KEY,"organizationId" TEXT NOT NULL,"schoolId" TEXT,"actorUserId" TEXT,"task" TEXT NOT NULL,"inputHash" TEXT NOT NULL,"outputSummary" TEXT,"risk" "AiRiskLevel" NOT NULL,"modelVersion" TEXT,"sourceRefs" JSONB,"humanConfirmed" BOOLEAN DEFAULT FALSE NOT NULL,"createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE INDEX ON "AiAuditLog" ("organizationId", "createdAt");
ALTER TABLE "School" ADD FOREIGN KEY ("organizationId") REFERENCES "Organization" ("id");
ALTER TABLE "User" ADD FOREIGN KEY ("organizationId") REFERENCES "Organization" ("id");
ALTER TABLE "User" ADD FOREIGN KEY ("schoolId") REFERENCES "School" ("id");
ALTER TABLE "Role" ADD FOREIGN KEY ("organizationId") REFERENCES "Organization" ("id");
ALTER TABLE "UserRole" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE;
ALTER TABLE "UserRole" ADD FOREIGN KEY ("roleId") REFERENCES "Role" ("id") ON DELETE CASCADE;
ALTER TABLE "FiscalYear" ADD FOREIGN KEY ("organizationId") REFERENCES "Organization" ("id");
ALTER TABLE "AcademicYear" ADD FOREIGN KEY ("organizationId") REFERENCES "Organization" ("id");
ALTER TABLE "StudentCount" ADD FOREIGN KEY ("academicYearId") REFERENCES "AcademicYear" ("id");
ALTER TABLE "BudgetSource" ADD FOREIGN KEY ("organizationId") REFERENCES "Organization" ("id");
ALTER TABLE "BudgetPool" ADD FOREIGN KEY ("schoolId") REFERENCES "School" ("id");
ALTER TABLE "BudgetPool" ADD FOREIGN KEY ("fiscalYearId") REFERENCES "FiscalYear" ("id");
ALTER TABLE "BudgetPool" ADD FOREIGN KEY ("budgetSourceId") REFERENCES "BudgetSource" ("id");
ALTER TABLE "BudgetPocket" ADD FOREIGN KEY ("budgetPoolId") REFERENCES "BudgetPool" ("id");
ALTER TABLE "BudgetTransaction" ADD FOREIGN KEY ("budgetPocketId") REFERENCES "BudgetPocket" ("id");
ALTER TABLE "BudgetTransaction" ADD FOREIGN KEY ("createdById") REFERENCES "User" ("id");
ALTER TABLE "Project" ADD FOREIGN KEY ("schoolId") REFERENCES "School" ("id");
ALTER TABLE "Project" ADD FOREIGN KEY ("fiscalYearId") REFERENCES "FiscalYear" ("id");
ALTER TABLE "Activity" ADD FOREIGN KEY ("projectId") REFERENCES "Project" ("id");
ALTER TABLE "ActivityBudget" ADD FOREIGN KEY ("activityId") REFERENCES "Activity" ("id");
ALTER TABLE "ActivityBudget" ADD FOREIGN KEY ("budgetPocketId") REFERENCES "BudgetPocket" ("id");
ALTER TABLE "Expense" ADD FOREIGN KEY ("activityId") REFERENCES "Activity" ("id");
ALTER TABLE "Attachment" ADD FOREIGN KEY ("expenseId") REFERENCES "Expense" ("id");
ALTER TABLE "ActivityReport" ADD FOREIGN KEY ("activityId") REFERENCES "Activity" ("id");
ALTER TABLE "WorkflowAction" ADD FOREIGN KEY ("workflowInstanceId") REFERENCES "WorkflowInstance" ("id");
ALTER TABLE "AuditLog" ADD FOREIGN KEY ("organizationId") REFERENCES "Organization" ("id");
ALTER TABLE "AuditLog" ADD FOREIGN KEY ("schoolId") REFERENCES "School" ("id");
ALTER TABLE "AuditLog" ADD FOREIGN KEY ("actorUserId") REFERENCES "User" ("id");
ALTER TABLE "Free15RuleSet" ADD FOREIGN KEY ("organizationId") REFERENCES "Organization" ("id");
ALTER TABLE "Free15RuleSet" ADD FOREIGN KEY ("academicYearId") REFERENCES "AcademicYear" ("id");
ALTER TABLE "Free15Rate" ADD FOREIGN KEY ("ruleSetId") REFERENCES "Free15RuleSet" ("id") ON DELETE CASCADE;
ALTER TABLE "Free15Calculation" ADD FOREIGN KEY ("schoolId") REFERENCES "School" ("id");
ALTER TABLE "Free15Calculation" ADD FOREIGN KEY ("academicYearId") REFERENCES "AcademicYear" ("id");
ALTER TABLE "Free15Calculation" ADD FOREIGN KEY ("ruleSetId") REFERENCES "Free15RuleSet" ("id");
ALTER TABLE "Free15CalculationItem" ADD FOREIGN KEY ("calculationId") REFERENCES "Free15Calculation" ("id") ON DELETE CASCADE;
ALTER TABLE "ProjectKpi" ADD FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE CASCADE;
ALTER TABLE "ProjectMember" ADD FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE CASCADE;
ALTER TABLE "ProjectMember" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE;
ALTER TABLE "Regulation" ADD FOREIGN KEY ("organizationId") REFERENCES "Organization" ("id");
ALTER TABLE "RegulationVersion" ADD FOREIGN KEY ("regulationId") REFERENCES "Regulation" ("id") ON DELETE CASCADE;
ALTER TABLE "RegulationRule" ADD FOREIGN KEY ("regulationVersionId") REFERENCES "RegulationVersion" ("id") ON DELETE CASCADE;
ALTER TABLE "RuleEvidence" ADD FOREIGN KEY ("regulationRuleId") REFERENCES "RegulationRule" ("id") ON DELETE CASCADE;
ALTER TABLE "AiAuditLog" ADD FOREIGN KEY ("organizationId") REFERENCES "Organization" ("id");
ALTER TABLE "AiAuditLog" ADD FOREIGN KEY ("schoolId") REFERENCES "School" ("id");
ALTER TABLE "AiAuditLog" ADD FOREIGN KEY ("actorUserId") REFERENCES "User" ("id");
COMMIT;
