import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { SchoolScopeService } from '../common/services/school-scope.service';
@Injectable()
export class ActivitiesService{
 constructor(private prisma:PrismaService,private scope:SchoolScopeService){}
 async list(u:any,projectId?:string){const where:any=projectId?{projectId}:{};where.project=u.roles?.includes('SUPER_ADMIN')?{school:{organizationId:u.organizationId}}:{schoolId:u.schoolId};return this.prisma.activity.findMany({where,include:{project:true,budgets:{include:{budgetPocket:{include:{budgetPool:true}}}},expenses:true,reports:true},orderBy:{name:'asc'}})}
 async get(u:any,id:string){const a=await this.prisma.activity.findFirst({where:{id,project:{school:{organizationId:u.organizationId}}},include:{project:{include:{school:true}},budgets:{include:{budgetPocket:{include:{budgetPool:true}}}},expenses:true,reports:true}});if(!a)throw new NotFoundException('Activity not found');this.scope.assertSameSchool(u,a.project.schoolId);return a}
 async create(u:any,d:any){const project=await this.prisma.project.findFirst({where:{id:d.projectId,school:{organizationId:u.organizationId}}});if(!project)throw new NotFoundException('Project not found');this.scope.assertSameSchool(u,project.schoolId);if(['APPROVED','CLOSED'].includes(project.status))throw new BadRequestException('Project is not editable');const activity=await this.prisma.activity.create({data:{projectId:project.id,name:d.name,allocatedBudget:new Prisma.Decimal(d.allocatedBudget??0)}});await this.prisma.auditLog.create({data:{organizationId:u.organizationId,schoolId:project.schoolId,actorUserId:u.id,action:'ACTIVITY_CREATED',entityType:'Activity',entityId:activity.id,metadata:{projectId:project.id}}});return activity}
 async update(u:any,id:string,d:any){const a=await this.get(u,id);if(['APPROVED','CLOSED'].includes(a.project.status))throw new BadRequestException('Project is not editable');const result=await this.prisma.activity.update({where:{id},data:{...(d.name!==undefined?{name:d.name}:{}),...(d.allocatedBudget!==undefined?{allocatedBudget:new Prisma.Decimal(d.allocatedBudget)}:{})}});await this.prisma.auditLog.create({data:{organizationId:u.organizationId,schoolId:a.project.schoolId,actorUserId:u.id,action:'ACTIVITY_UPDATED',entityType:'Activity',entityId:id,metadata:{changed:Object.keys(d)}}});return result}
 async addBudget(u:any,id:string,d:any){const a=await this.get(u,id);const pocket=await this.prisma.budgetPocket.findFirst({where:{id:d.budgetPocketId,budgetPool:{schoolId:a.project.schoolId}}});if(!pocket)throw new ForbiddenException('Budget pocket is outside activity school scope');const result=await this.prisma.activityBudget.upsert({where:{activityId_budgetPocketId:{activityId:id,budgetPocketId:pocket.id}},update:{amount:new Prisma.Decimal(d.amount)},create:{activityId:id,budgetPocketId:pocket.id,amount:new Prisma.Decimal(d.amount)}});await this.prisma.auditLog.create({data:{organizationId:u.organizationId,schoolId:a.project.schoolId,actorUserId:u.id,action:'ACTIVITY_BUDGET_MAPPED',entityType:'ActivityBudget',entityId:result.id,metadata:{activityId:id,budgetPocketId:pocket.id,amount:String(d.amount)}}});return result}
 async report(u:any,id:string,d:any){const a=await this.get(u,id);if(d.progressPercent<0||d.progressPercent>100)throw new BadRequestException('progressPercent must be between 0 and 100');const report=await this.prisma.activityReport.create({data:{activityId:id,progressPercent:d.progressPercent,summary:d.summary}});await this.prisma.auditLog.create({data:{organizationId:u.organizationId,schoolId:a.project.schoolId,actorUserId:u.id,action:'ACTIVITY_REPORT_CREATED',entityType:'ActivityReport',entityId:report.id,metadata:{activityId:id,progressPercent:d.progressPercent}}});return report}
}
