export const PROJECT_WRITE_ROLES=['SUPER_ADMIN','ORG_ADMIN','SCHOOL_ADMIN','DIRECTOR','PLANNING_OFFICER','TEACHER'];
export const ACTIVITY_WRITE_ROLES=['SUPER_ADMIN','ORG_ADMIN','SCHOOL_ADMIN','DIRECTOR','PLANNING_OFFICER','TEACHER'];
export const EXPENSE_WRITE_ROLES=['SUPER_ADMIN','ORG_ADMIN','SCHOOL_ADMIN','FINANCE_OFFICER'];
export const REPORT_WRITE_ROLES=['SUPER_ADMIN','ORG_ADMIN','SCHOOL_ADMIN','DIRECTOR','PLANNING_OFFICER','TEACHER'];
export const WORKFLOW_SUBMIT_ROLES=['SUPER_ADMIN','ORG_ADMIN','SCHOOL_ADMIN','DIRECTOR','PLANNING_OFFICER','TEACHER'];
export const WORKFLOW_APPROVER_BY_STEP:Record<number,string[]>={1:['SUPER_ADMIN','PLANNING_OFFICER','SCHOOL_ADMIN'],2:['SUPER_ADMIN','SCHOOL_ADMIN','ORG_ADMIN'],3:['SUPER_ADMIN','ORG_ADMIN'],4:['SUPER_ADMIN','DIRECTOR']};
