import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma, BudgetTransactionType } from '@prisma/client';
import { calculateLedger } from '../common/domain/budget-ledger';
import { PrismaService } from '../prisma/prisma.service';
import { CreateBudgetPocketDto, CreateBudgetPoolDto, CreateBudgetSourceDto, PostBudgetTransactionDto } from './dto';
const SUB=new Set<BudgetTransactionType>(['TRANSFER_OUT','COMMITMENT','EXPENSE']);
@Injectable()
export class BudgetService{
 constructor(private prisma:PrismaService){}
 private schoolWhere(user:any){return user.roles.includes('SUPER_ADMIN')?{}:user.schoolId?{schoolId:user.schoolId}:{school:{organizationId:user.organizationId}}}
 sources(user:any){return this.prisma.budgetSource.findMany({where:{organizationId:user.organizationId,isActive:true},orderBy:{code:'asc'}})}
 createSource(user:any,dto:CreateBudgetSourceDto){return this.prisma.budgetSource.create({data:{...dto,organizationId:user.organizationId}})}
 pools(user:any){return this.prisma.budgetPool.findMany({where:this.schoolWhere(user),include:{budgetSource:true,fiscalYear:true,pockets:true},orderBy:{createdAt:'desc'}})}
 async createPool(user:any,dto:CreateBudgetPoolDto){if(!user.roles.includes('SUPER_ADMIN')&&user.schoolId!==dto.schoolId)throw new ForbiddenException('Outside school scope');const school=await this.prisma.school.findFirst({where:{id:dto.schoolId,organizationId:user.organizationId}});const fy=await this.prisma.fiscalYear.findFirst({where:{id:dto.fiscalYearId,organizationId:user.organizationId}});const source=await this.prisma.budgetSource.findFirst({where:{id:dto.budgetSourceId,organizationId:user.organizationId,isActive:true}});if(!school||!fy||!source)throw new BadRequestException('Budget pool references must belong to the current organization');return this.prisma.budgetPool.create({data:dto})}
 async createPocket(user:any,dto:CreateBudgetPocketDto){const pool=await this.prisma.budgetPool.findUnique({where:{id:dto.budgetPoolId}});if(!pool)throw new NotFoundException('Budget pool not found');if(!user.roles.includes('SUPER_ADMIN')&&user.schoolId!==pool.schoolId)throw new ForbiddenException('Outside school scope');return this.prisma.budgetPocket.create({data:dto})}
 async balance(user:any,pocketId:string){const pocket=await this.prisma.budgetPocket.findUnique({where:{id:pocketId},include:{budgetPool:true}});if(!pocket)throw new NotFoundException('Budget pocket not found');if(!user.roles.includes('SUPER_ADMIN')&&user.schoolId!==pocket.budgetPool.schoolId)throw new ForbiddenException('Outside school scope');const txs=await this.prisma.budgetTransaction.findMany({where:{budgetPocketId:pocketId,status:'POSTED'}});const result=calculateLedger(txs.map(tx=>({type:tx.type as any,amount:Number(tx.amount)})));return{pocketId,available:new Prisma.Decimal(result.available).toFixed(2),commitments:new Prisma.Decimal(result.commitments).toFixed(2),actualExpenses:new Prisma.Decimal(result.actualExpenses).toFixed(2),transactionCount:txs.length}}
 async post(user:any,dto:PostBudgetTransactionDto){return this.prisma.$transaction(async tx=>{const pocket=await tx.budgetPocket.findUnique({where:{id:dto.budgetPocketId},include:{budgetPool:true}});if(!pocket)throw new NotFoundException('Budget pocket not found');if(!user.roles.includes('SUPER_ADMIN')&&user.schoolId!==pocket.budgetPool.schoolId)throw new ForbiddenException('Outside school scope');const txs=await tx.budgetTransaction.findMany({where:{budgetPocketId:dto.budgetPocketId,status:'POSTED'}});const ledger=calculateLedger(txs.map(item=>({type:item.type as any,amount:Number(item.amount)})));if(SUB.has(dto.type as BudgetTransactionType)&&new Prisma.Decimal(ledger.available).lt(dto.amount))throw new BadRequestException('Insufficient available budget');const item=await tx.budgetTransaction.create({data:{budgetPocketId:dto.budgetPocketId,type:dto.type as BudgetTransactionType,amount:new Prisma.Decimal(dto.amount),referenceType:dto.referenceType,referenceId:dto.referenceId,note:dto.note,status:'POSTED',postedAt:new Date(),createdById:user.id}});await tx.auditLog.create({data:{organizationId:user.organizationId,schoolId:pocket.budgetPool.schoolId,actorUserId:user.id,action:'BUDGET_TRANSACTION_POSTED',entityType:'BudgetTransaction',entityId:item.id,metadata:{type:item.type,amount:item.amount.toString(),budgetPocketId:item.budgetPocketId}}});return item},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
}
