import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { calculateLedger } from '../common/domain/budget-ledger';
import { SchoolScopeService } from '../common/services/school-scope.service';
@Injectable()
export class ExpensesService{
 constructor(private prisma:PrismaService,private scope:SchoolScopeService){}
 async list(u:any,activityId?:string){const schoolScope=u.roles?.includes('SUPER_ADMIN')?{school:{organizationId:u.organizationId}}:{schoolId:u.schoolId};const where:any=activityId?{activityId,activity:{project:schoolScope}}:{activity:{project:schoolScope}};return this.prisma.expense.findMany({where,include:{activity:{include:{project:true}},attachments:true},orderBy:{expenseDate:'desc'}})}
 async get(u:any,id:string){const expense=await this.prisma.expense.findFirst({where:{id,activity:{project:{school:{organizationId:u.organizationId}}}},include:{activity:{include:{project:{include:{school:true}}}},attachments:true}});if(!expense)throw new NotFoundException('Expense not found');this.scope.assertSameSchool(u,expense.activity.project.schoolId);return expense}
 async create(u:any,d:any){const amount=new Prisma.Decimal(d.amount);const activity=await this.prisma.activity.findFirst({where:{id:d.activityId,project:{school:{organizationId:u.organizationId}}},include:{project:true,budgets:true}});if(!activity)throw new NotFoundException('Activity not found');this.scope.assertSameSchool(u,activity.project.schoolId);if(activity.project.status!=='APPROVED')throw new BadRequestException('Project must be APPROVED before expenses can be posted');const mapping=activity.budgets.find(x=>x.budgetPocketId===d.budgetPocketId);if(!mapping)throw new BadRequestException('Activity is not mapped to this budget pocket');const pocket=await this.prisma.budgetPocket.findFirst({where:{id:d.budgetPocketId,budgetPool:{schoolId:activity.project.schoolId}}});if(!pocket)throw new ForbiddenException('Budget pocket is outside school scope');const txs=await this.prisma.budgetTransaction.findMany({where:{budgetPocketId:pocket.id,status:'POSTED'}});const ledger=calculateLedger(txs.map(tx=>({type:tx.type as any,amount:Number(tx.amount)})));if(amount.gt(ledger.available))throw new BadRequestException('Insufficient available budget');const mappedSpent=await this.prisma.expense.aggregate({where:{activityId},_sum:{amount:true}});const alreadySpent=new Prisma.Decimal(mappedSpent._sum.amount??0);if(alreadySpent.add(amount).gt(mapping.amount))throw new BadRequestException('Expense exceeds activity budget mapping');return this.prisma.$transaction(async tx=>{const expense=await tx.expense.create({data:{activityId,amount,description:d.description,expenseDate:new Date(d.expenseDate)}});await tx.budgetTransaction.create({data:{budgetPocketId:pocket.id,type:'EXPENSE',status:'POSTED',amount,referenceType:'Expense',referenceId:expense.id,note:d.description,postedAt:new Date(),createdById:u.id}});await tx.auditLog.create({data:{organizationId:u.organizationId,schoolId:activity.project.schoolId,actorUserId:u.id,action:'EXPENSE_POSTED',entityType:'Expense',entityId:expense.id,metadata:{activityId,budgetPocketId:pocket.id,amount:amount.toString()}}});return expense})}
 async update(u:any,id:string,d:any){await this.get(u,id);throw new ConflictException('Posted expenses are immutable; create a reversal/correction workflow instead')}
}
