import Link from 'next/link';
import { Card } from '../../../components/ui/Card';

export default function ProjectEditPage() {
  return <div className="page-stack">
    <div className="breadcrumb"><Link href="/projects">โครงการ</Link><span>/</span><span>สร้าง/แก้ไข</span></div>
    <div className="page-header"><div><p className="eyebrow">PROJECT FORM</p><h1>สร้างโครงการ</h1><p className="muted">กรอกข้อมูลตามลำดับเพื่อให้ Project → Activity → Expense เชื่อมกันตั้งแต่ต้น</p></div></div>
    <form className="page-stack">
      <Card><div className="section-heading"><h2>1. ข้อมูลพื้นฐาน</h2><span className="required-note">* จำเป็น</span></div><div className="form-grid"><div className="form-field"><label htmlFor="code">รหัสโครงการ *</label><input id="code" defaultValue="PRJ-2569-005" required /></div><div className="form-field"><label htmlFor="name">ชื่อโครงการ *</label><input id="name" placeholder="เช่น โครงการส่งเสริมการอ่าน" required /></div><div className="form-field"><label htmlFor="year">ปีงบประมาณ *</label><select id="year" defaultValue="2569"><option>2569</option><option>2570</option><option>2571</option></select></div><div className="form-field"><label htmlFor="source">แหล่งเงิน *</label><select id="source"><option>เงินอุดหนุน</option><option>เรียนฟรี 15 ปี</option></select></div></div></Card>
      <Card><div className="section-heading"><h2>2. แผนงานและขอบเขต</h2></div><div className="form-grid"><div className="form-field full"><label htmlFor="rationale">หลักการและเหตุผล *</label><textarea id="rationale" rows={4} placeholder="อธิบายปัญหา/ความจำเป็นและความเชื่อมโยงกับแผน"></textarea></div><div className="form-field full"><label htmlFor="objective">วัตถุประสงค์ *</label><textarea id="objective" rows={4} placeholder="ระบุผลที่ต้องการบรรลุ"></textarea></div><div className="form-field"><label htmlFor="target">กลุ่มเป้าหมาย *</label><input id="target" placeholder="นักเรียน ป.4–ม.3" /></div><div className="form-field"><label htmlFor="benefit">จำนวนผู้รับประโยชน์</label><input id="benefit" type="number" min="0" placeholder="200" /></div></div></Card>
      <Card><div className="section-heading"><h2>3. ระยะเวลาและงบประมาณ</h2></div><div className="form-grid"><div className="form-field"><label htmlFor="start">วันเริ่มต้น *</label><input id="start" type="date" required /></div><div className="form-field"><label htmlFor="end">วันสิ้นสุด *</label><input id="end" type="date" required /></div><div className="form-field"><label htmlFor="budget">งบประมาณที่วางแผน *</label><input id="budget" type="number" min="0" step="0.01" placeholder="100000.00" required /></div><div className="form-field"><label htmlFor="pocket">Budget Pocket</label><select id="pocket"><option>เลือกตามแหล่งเงิน</option><option>กิจกรรมพัฒนาผู้เรียน</option><option>วัสดุการศึกษา</option></select></div></div></Card>
      <Card><div className="section-heading"><h2>4. ผู้รับผิดชอบและ KPI</h2></div><div className="form-grid"><div className="form-field"><label htmlFor="owner">ผู้รับผิดชอบหลัก *</label><select id="owner"><option>นางสาวณัฐริกา อุปพงษ์</option><option>นายสมชาย ใจดี</option></select></div><div className="form-field"><label htmlFor="kpi">KPI หลัก *</label><input id="kpi" placeholder="นักเรียนเข้าร่วมไม่น้อยกว่า 200 คน" /></div><div className="form-field"><label htmlFor="targetValue">ค่าเป้าหมาย</label><input id="targetValue" placeholder="200" /></div><div className="form-field"><label htmlFor="unit">หน่วย</label><input id="unit" placeholder="คน" /></div></div></Card>
      <div className="form-actions"><Link className="btn btn-secondary btn-md" href="/projects">ยกเลิก</Link><button className="btn btn-secondary btn-md" type="button">บันทึกแบบร่าง</button><button className="btn btn-primary btn-md" type="submit">บันทึกและส่งตรวจ</button></div>
    </form>
  </div>;
}
