BEGIN;
ALTER TABLE "BudgetTransaction" ALTER COLUMN "status" SET DEFAULT 'DRAFT';
ALTER TABLE "Project" ALTER COLUMN "status" SET DEFAULT 'DRAFT';
ALTER TABLE "Activity" ALTER COLUMN "status" SET DEFAULT 'PLANNED';
ALTER TABLE "WorkflowInstance" ALTER COLUMN "currentStep" SET DEFAULT 1;
ALTER TABLE "Free15RuleSet" ALTER COLUMN "status" SET DEFAULT 'DRAFT';
ALTER TABLE "Free15Calculation" ALTER COLUMN "status" SET DEFAULT 'PREVIEW';
ALTER TABLE "AiAuditLog" ALTER COLUMN "risk" SET DEFAULT 'LOW';
COMMIT;
